import type { ChipProps } from "@mui/material";

export const SOS_STATUS = {
  pending: "PENDING",
  verified: "VERIFIED",
  rejected: "REJECTED",
  assigned: "ASSIGNED",
  inProgress: "IN_PROGRESS",
  completed: "COMPLETED",
  confirmed: "CONFIRMED",
} as const;

export const MISSION_STATUS = {
  assigned: "ASSIGNED",
  enRoute: "EN_ROUTE",
  onSite: "ON_SITE",
  inProgress: "IN_PROGRESS",
  completed: "COMPLETED",
  closed: "CLOSED",
  cancelled: "CANCELLED",
} as const;

export const SHIPMENT_STATUS = {
  preparing: "PREPARING",
  dispatched: "DISPATCHED",
  shipped: "SHIPPED",
  inTransit: "IN_TRANSIT",
  delivered: "DELIVERED",
  verified: "VERIFIED",
} as const;

export const CAMPAIGN_STATUS = {
  draft: "DRAFT",
  active: "ACTIVE",
  paused: "PAUSED",
  completed: "COMPLETED",
  closed: "CLOSED",
} as const;

export const PRIORITY = {
  critical: "CRITICAL",
  high: "HIGH",
  medium: "MEDIUM",
  low: "LOW",
} as const;

export const STATUS_LABELS: Record<string, string> = {
  PENDING: "Đang chờ",
  VERIFIED: "Đã xác minh",
  REJECTED: "Từ chối",
  ASSIGNED: "Đã phân công",
  EN_ROUTE: "Đang di chuyển",
  ON_SITE: "Tại hiện trường",
  IN_PROGRESS: "Đang xử lý",
  COMPLETED: "Hoàn tất",
  CONFIRMED: "Đã xác nhận",
  CLOSED: "Đã đóng",
  CANCELLED: "Đã hủy",
  CANCELED: "Đã hủy",
  PREPARING: "Đang chuẩn bị",
  DISPATCHED: "Đã điều phối",
  SHIPPED: "Đã gửi",
  IN_TRANSIT: "Đang vận chuyển",
  DELIVERED: "Đã bàn giao",
  ACTIVE: "Đang hoạt động",
  PAUSED: "Tạm dừng",
  DRAFT: "Bản nháp",
  EXECUTED: "Đã thực hiện",
  FAILED: "Thất bại",
  INITIATED: "Đã khởi tạo",
  PROCESSING: "Đang xử lý",
  CRITICAL: "Nguy cấp",
  URGENT: "Khẩn cấp",
  WARNING: "Cảnh báo",
  HIGH: "Cao",
  MEDIUM: "Trung bình",
  LOW: "Thấp",
  OPEN: "Đang mở",
  INVESTIGATING: "Đang xác minh",
  RESOLVED: "Đã xử lý",
  DISMISSED: "Đã bác bỏ",
  SUSPENDED: "Tạm khóa",
  INACTIVE: "Không hoạt động",
  AVAILABLE: "Sẵn sàng",
  IN_USE: "Đang sử dụng",
  MAINTENANCE: "Bảo trì",
  APPROVED: "Đã duyệt",
  SUBMITTED: "Đã gửi duyệt",
  REVIEW: "Đang xem xét",
  RESERVED: "Đã giữ chỗ",
  PAID: "Đã thanh toán",
  SUCCESS: "Thành công",
  ERROR: "Có lỗi",
  LOW_STOCK: "Sắp hết hàng",
  CHECK_IN: "Đã check-in",
  CHECK_OUT: "Đã check-out",
  CHECKIN: "Đã check-in",
  CHECKOUT: "Đã check-out",
  READY: "Sẵn sàng",
  DONE: "Hoàn tất",
  IDLE: "Sẵn sàng",
  SAN_SANG: "Sẵn sàng",
  PENDING_APPROVAL: "Chờ phê duyệt",
  WAITING_APPROVAL: "Chờ phê duyệt",
  AWAITING_APPROVAL: "Chờ phê duyệt",
  UNDER_REVIEW: "Đang thẩm định",
  IN_REVIEW: "Đang thẩm định",
  HELD: "Đã giữ ngân sách",
  BUDGET_HELD: "Đã giữ ngân sách",
  BUDGET_LOCKED: "Đã khóa ngân sách",
  PAYMENT_COMPLETED: "Đã thanh toán",
  DISTRIBUTING: "Đang phân phối",
};

export const STATUS_COLORS: Record<string, ChipProps["color"]> = {
  PENDING: "warning",
  VERIFIED: "info",
  ASSIGNED: "secondary",
  EN_ROUTE: "info",
  ON_SITE: "info",
  IN_PROGRESS: "primary",
  COMPLETED: "success",
  CONFIRMED: "success",
  CLOSED: "default",
  CANCELLED: "error",
  REJECTED: "error",
  PREPARING: "warning",
  DISPATCHED: "info",
  SHIPPED: "info",
  IN_TRANSIT: "primary",
  DELIVERED: "success",
  ACTIVE: "success",
  PAUSED: "warning",
  DRAFT: "default",
  EXECUTED: "success",
  FAILED: "error",
  CRITICAL: "error",
  HIGH: "warning",
  MEDIUM: "info",
  LOW: "success",
  OPEN: "warning",
  INVESTIGATING: "info",
  RESOLVED: "success",
  SUSPENDED: "error",
  INACTIVE: "default",
};
